/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautyparlour.frames;

import beautyparlour.bean.CustomerBean;
import beautyparlour.bean.CustomerServiceReportBean;
import beautyparlour.bean.DailyReportBean;
import beautyparlour.bean.DailyServiceReportBean;
import beautyparlour.dao.CustomerServiceReportDao;
import beautyparlour.dao.ServiceReportDao;
import beautyparlour.daoImpl.CustomerDaoImpl;
import beautyparlour.daoImpl.CustomerServiceReportDaoImpl1;
import beautyparlour.daoImpl.ReportDaoImpl;
import beautyparlour.daoImpl.ServiceReportDaoImpl;
import java.awt.Color;
import java.awt.Font;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dell
 */
public class ClientServiceReportPage extends javax.swing.JFrame {

    /**
     * Creates new form DailyReportPage
     */
    DefaultTableModel tableModelCustomerServiceReport;
    CustomerServiceReportDao CustomerServiceReportObj;
    public ArrayList<CustomerServiceReportBean> customer_service_report_list;

    TableRowSorter<DefaultTableModel> rowSorter = null;

    public ClientServiceReportPage() {
        initComponents();
                this.getContentPane().setBackground(Color.white);

        CustomerServiceReportObj = new CustomerServiceReportDaoImpl1();
        tableModelCustomerServiceReport = (DefaultTableModel) this.jTableReport.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelCustomerServiceReport);
        this.jTableReport.setRowSorter(rowSorter);
        LocalDate date = LocalDate.now();

        showInTable(date+"");
        dateLabel.setText("Today's Report");

    }

    public void showInTable(String date) {
        int total_amount=0;
        int total_customers=0;
        tableModelCustomerServiceReport.setRowCount(0);

        int serial = 0;
        customer_service_report_list = CustomerServiceReportObj.getCustomerServiceReport(date);

        for (CustomerServiceReportBean obj : customer_service_report_list) {
            Vector V = new Vector();
            serial++;

            V.add(serial);
            V.add(obj.getCustomer());
            V.add(obj.getServices());
            V.add(obj.getPrice());

        total_customers+=obj.getServices();
        total_amount+=obj.getPrice();
            tableModelCustomerServiceReport.addRow(V);
        }

        
        totatCustomerlabel.setText(""+total_customers);
        totatProfitlabel.setText(""+total_amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totatCustomerlabel = new javax.swing.JLabel();
        totatProfitlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(60, 34, 19));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, 30));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date:");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Services:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 517, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Amount:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 557, -1, -1));

        totatCustomerlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totatCustomerlabel.setForeground(new java.awt.Color(255, 255, 255));
        totatCustomerlabel.setText("0");
        getContentPane().add(totatCustomerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 517, -1, -1));

        totatProfitlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totatProfitlabel.setForeground(new java.awt.Color(255, 255, 255));
        totatProfitlabel.setText("0");
        getContentPane().add(totatProfitlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 557, -1, -1));

        jPanel1.setBackground(new java.awt.Color(20, 11, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(60, 34, 19));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THE BEAUTY BAR");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 750, 30));

        jTableReport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S#", "Customer", "No.Service", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableReport);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 728, 329));

        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });
        jPanel1.add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 181, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pick a date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Service Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 300, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/report.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        jButtonBack1.setBackground(new java.awt.Color(60, 34, 19));
        jButtonBack1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/print_1.png"))); // NOI18N
        jButtonBack1.setText("Print Report");
        jButtonBack1.setFocusPainted(false);
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ReportPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        // TODO add your handling code here:

//        String date=jXDatePicker2.getDate().toString();
//        System.out.println(""+date);
         Calendar cals = Calendar.getInstance();
    SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
   String date2= formater.format(this.jXDatePicker2.getDate());
   LocalDate a= LocalDate.parse(date2);

    System.out.println(a.getMonth().name());
     
        showInTable(date2);
                LocalDate date = LocalDate.now();

        if(date2.equals(date+"")){
                dateLabel.setText("Today's Report");
        }
        else{
                        dateLabel.setText("Report of Date: "+a.getMonth().name());

        }



    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        MessageFormat header = new MessageFormat("THE BEAUTY BAR REPORT Service "+this.dateLabel.getText().toString());
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            this.jTableReport.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception ex) {
            Logger.getLogger(InventoryPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBack1ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientServiceReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientServiceReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientServiceReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientServiceReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientServiceReportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableReport;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel totatCustomerlabel;
    private javax.swing.JLabel totatProfitlabel;
    // End of variables declaration//GEN-END:variables
}
