/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautyparlour.frames;

import beautyparlour.bean.ProductSaleBean;
import beautyparlour.bean.ProductSaleDetailBean;
import beautyparlour.bean.SaleBeans;
import beautyparlour.bean.SaleDetailBeans;
import beautyparlour.dao.CustomerDao;
import beautyparlour.dao.ProductSaleDao;
import beautyparlour.dao.ProductSaleDetailDao;
import beautyparlour.dao.SaleDao;
import beautyparlour.dao.SaleDetailsDao;
import beautyparlour.dao.ServiceDao;
import beautyparlour.daoImpl.CustomerDaoImpl;
import beautyparlour.daoImpl.ProductSaleDaoImpl;
import beautyparlour.daoImpl.ProductSaleDetailDaoImpl;
import beautyparlour.daoImpl.SaleDaoImpl;
import beautyparlour.daoImpl.SaleDetailDapImpl;
import beautyparlour.daoImpl.ServiceDaoImpl;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.io.File;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vksoni
 */
public class CustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    DefaultTableModel tableModelCustomerSaleDetail;
    DefaultTableModel tableModelCustomerSale;

    DefaultTableModel tableModelProductCustomerSaleDetail;
    DefaultTableModel tableModelProductCustomerSale;
    public ArrayList<SaleDetailBeans> sale_details_list;
    public ArrayList<ProductSaleDetailBean> productSaleDetails;

    public ArrayList<SaleBeans> sale_list;
    public ArrayList<ProductSaleBean> productSalesList;

    ArrayList<SaleDetailBeans> sales_detail_list;
    SaleDetailsDao saleDeatail;
    SaleDao sale;
    ProductSaleDetailDao productSaleDeatailDao;
    ProductSaleDao productSaleDao;
    ServiceDao servicedao;

    CustomerDao customerDao;
    // DebtDetailDao debtDao;
    int cust_id;

    public CustomerDetails() {
        initComponents();
    }
    int customer_id;

    public CustomerDetails(int customer_id) {

        initComponents();
        this.customer_id = customer_id;
        saleDeatail = new SaleDetailDapImpl();
//        debtDao = new DebtDaoImpl();
        sale = new SaleDaoImpl();
        servicedao = new ServiceDaoImpl();
        productSaleDeatailDao = new ProductSaleDetailDaoImpl();
        productSaleDao = new ProductSaleDaoImpl();
        tableModelCustomerSaleDetail = (DefaultTableModel) this.jTableCustomerSaleDetail.getModel();
        tableModelCustomerSale = (DefaultTableModel) this.jTableCustomerSale.getModel();

        tableModelProductCustomerSaleDetail = (DefaultTableModel) this.jTableCustomerProductSaleDetail1.getModel();;
        tableModelProductCustomerSale = (DefaultTableModel) this.jTableCustomerProductSale.getModel();;

        customerDao = new CustomerDaoImpl();
        this.jButtonUpdateMoney.setVisible(false);
        this.jButtonUpdate.setVisible(true);
        this.jTextFieldUpdateMoney.setVisible(false);
        this.jLabelCustomerName.setText(customerDao.getCustomerById(customer_id).getCustomer_name());

        this.jLabelCustomerDebt.setText("" + customerDao.getCustomerById(customer_id).getCustomer_dept());
        this.jLabelAddMoney.setVisible(false);
        cust_id = customer_id;

        this.jRadioButtonDeposite.setVisible(false);
        this.jRadioWithDraw.setVisible(false);
        showInSaleTable(customer_id);
        showInProductSaleTable(customer_id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCustomerSaleDetail = new javax.swing.JTable();
        jLabelAddMoney = new javax.swing.JLabel();
        jLabelCustomerName = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelCustomerDebt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonUpdateMoney = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldUpdateMoney = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCustomerSale = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCustomerProductSale = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCustomerProductSaleDetail1 = new javax.swing.JTable();
        jRadioWithDraw = new javax.swing.JRadioButton();
        jRadioButtonDeposite = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonBack2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 11, 6));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCustomerSaleDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCustomerSaleDetail.setForeground(new java.awt.Color(0, 0, 51));
        jTableCustomerSaleDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Services", "cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCustomerSaleDetail.setToolTipText("Products");
        jTableCustomerSaleDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCustomerSaleDetail.setGridColor(new java.awt.Color(0, 0, 51));
        jTableCustomerSaleDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerSaleDetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCustomerSaleDetail);
        if (jTableCustomerSaleDetail.getColumnModel().getColumnCount() > 0) {
            jTableCustomerSaleDetail.getColumnModel().getColumn(1).setMinWidth(100);
            jTableCustomerSaleDetail.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCustomerSaleDetail.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 410, 210));

        jLabelAddMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddMoney.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddMoney.setText("Enter Amount");
        jPanel1.add(jLabelAddMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, -1));

        jLabelCustomerName.setBackground(new java.awt.Color(60, 34, 19));
        jLabelCustomerName.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabelCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerName.setText("Customer name");
        jLabelCustomerName.setBorder(new javax.swing.border.MatteBorder(null));
        jLabelCustomerName.setOpaque(true);
        jPanel1.add(jLabelCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 570, 50));

        jButtonBack.setBackground(new java.awt.Color(20, 11, 6));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.setFocusPainted(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabelCustomerDebt.setBackground(new java.awt.Color(60, 34, 19));
        jLabelCustomerDebt.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 36)); // NOI18N
        jLabelCustomerDebt.setForeground(new java.awt.Color(51, 255, 0));
        jLabelCustomerDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerDebt.setText("0.0");
        jLabelCustomerDebt.setOpaque(true);
        jPanel1.add(jLabelCustomerDebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Service Provided Details");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 240, 40));

        jButtonUpdateMoney.setBackground(new java.awt.Color(20, 11, 6));
        jButtonUpdateMoney.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUpdateMoney.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateMoney.setText("Update Money");
        jButtonUpdateMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateMoneyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 230, 30));

        jButtonUpdate.setBackground(new java.awt.Color(20, 11, 6));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update Account");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 230, 30));

        jTextFieldUpdateMoney.setBackground(new java.awt.Color(20, 11, 6));
        jTextFieldUpdateMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUpdateMoney.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUpdateMoney.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jTextFieldUpdateMoney.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUpdateMoney.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldUpdateMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUpdateMoneyMouseClicked(evt);
            }
        });
        jTextFieldUpdateMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpdateMoneyActionPerformed(evt);
            }
        });
        jTextFieldUpdateMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUpdateMoneyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUpdateMoneyKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldUpdateMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Remaining Money");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        jTableCustomerSale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableCustomerSale.setForeground(new java.awt.Color(0, 0, 51));
        jTableCustomerSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale Id ", "Sale Date", "Discount", "Total Amount", "Paid", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCustomerSale.setToolTipText("Customer Record");
        jTableCustomerSale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCustomerSale.setGridColor(new java.awt.Color(0, 0, 51));
        jTableCustomerSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerSaleMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableCustomerSaleMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCustomerSale);
        if (jTableCustomerSale.getColumnModel().getColumnCount() > 0) {
            jTableCustomerSale.getColumnModel().getColumn(0).setMinWidth(60);
            jTableCustomerSale.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableCustomerSale.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableCustomerSale.getColumnModel().getColumn(1).setMinWidth(90);
            jTableCustomerSale.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTableCustomerSale.getColumnModel().getColumn(1).setMaxWidth(90);
            jTableCustomerSale.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTableCustomerSale.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTableCustomerSale.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 610, 210));

        jTableCustomerProductSale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableCustomerProductSale.setForeground(new java.awt.Color(0, 0, 51));
        jTableCustomerProductSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Sale Id ", "Sale Date", "Discount", "Total Amount", "Paid", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCustomerProductSale.setToolTipText("Customer Record");
        jTableCustomerProductSale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCustomerProductSale.setGridColor(new java.awt.Color(0, 0, 51));
        jTableCustomerProductSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerProductSaleMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableCustomerProductSaleMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTableCustomerProductSale);
        if (jTableCustomerProductSale.getColumnModel().getColumnCount() > 0) {
            jTableCustomerProductSale.getColumnModel().getColumn(0).setMinWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(0).setMaxWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(1).setMinWidth(100);
            jTableCustomerProductSale.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCustomerProductSale.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableCustomerProductSale.getColumnModel().getColumn(2).setMinWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(2).setMaxWidth(90);
            jTableCustomerProductSale.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTableCustomerProductSale.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTableCustomerProductSale.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 620, 210));

        jTableCustomerProductSaleDetail1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCustomerProductSaleDetail1.setForeground(new java.awt.Color(0, 0, 51));
        jTableCustomerProductSaleDetail1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Cost (Rs)", "QTY", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCustomerProductSaleDetail1.setToolTipText("Products");
        jTableCustomerProductSaleDetail1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCustomerProductSaleDetail1.setGridColor(new java.awt.Color(0, 0, 51));
        jTableCustomerProductSaleDetail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerProductSaleDetail1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableCustomerProductSaleDetail1);
        if (jTableCustomerProductSaleDetail1.getColumnModel().getColumnCount() > 0) {
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(1).setMinWidth(100);
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(2).setMinWidth(40);
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableCustomerProductSaleDetail1.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 400, 210));

        jRadioWithDraw.setBackground(new java.awt.Color(60, 34, 19));
        buttonGroup2.add(jRadioWithDraw);
        jRadioWithDraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioWithDraw.setForeground(new java.awt.Color(255, 255, 255));
        jRadioWithDraw.setText("Withdraw Money");
        jPanel1.add(jRadioWithDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 240, -1));

        jRadioButtonDeposite.setBackground(new java.awt.Color(60, 34, 19));
        buttonGroup2.add(jRadioButtonDeposite);
        jRadioButtonDeposite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonDeposite.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDeposite.setText("Deposite Money");
        jPanel1.add(jRadioButtonDeposite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Products Sales Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 210, 30));

        jButtonBack1.setBackground(new java.awt.Color(60, 34, 19));
        jButtonBack1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/print_1.png"))); // NOI18N
        jButtonBack1.setText("Print Services Report");
        jButtonBack1.setFocusPainted(false);
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 240, 40));

        jButtonBack2.setBackground(new java.awt.Color(60, 34, 19));
        jButtonBack2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/print_1.png"))); // NOI18N
        jButtonBack2.setText("Print Product Report");
        jButtonBack2.setFocusPainted(false);
        jButtonBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 630));

        jLabel1.setBackground(new java.awt.Color(60, 34, 19));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Signature Beauty Parlour");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1320, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCustomerSaleDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerSaleDetailMouseClicked


    }//GEN-LAST:event_jTableCustomerSaleDetailMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new ShowCustomerPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonUpdateMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateMoneyActionPerformed
        // TODO add your handling code here:
        int dialogButton = 0;
        if (this.jRadioWithDraw.isSelected() || this.jRadioButtonDeposite.isSelected()) {
            if (!this.jTextFieldUpdateMoney.getText().equalsIgnoreCase("")) {
                try {
                    double debt = Double.parseDouble("" + this.jLabelCustomerDebt.getText());
                    double addMoney = Double.parseDouble(this.jTextFieldUpdateMoney.getText());
                    double newDebt = 0.0;
                    if (this.jRadioButtonDeposite.isSelected()) {
                        newDebt = debt + addMoney;
                        dialogButton = JOptionPane.showConfirmDialog(null, "Are you sure you wanna desposite " + addMoney + " to " + this.jLabelCustomerName.getText() + " account. ", "Update record", JOptionPane.YES_NO_OPTION);

                    }
                    if (this.jRadioWithDraw.isSelected()) {
                        newDebt = debt - addMoney;
                        dialogButton = JOptionPane.showConfirmDialog(null, "Are you sure you wanna withdraw " + addMoney + " from " + this.jLabelCustomerName.getText() + " account. ", "Update record", JOptionPane.YES_NO_OPTION);

                    }

                    if (dialogButton == JOptionPane.YES_OPTION) {

                        int i = customerDao.modifyCustomerDebt(cust_id, newDebt);

                        if (i > 0) {
                            JOptionPane.showMessageDialog(rootPane, "Updated Successfully!");
                            this.jButtonUpdate.setVisible(true);
                            this.jButtonUpdateMoney.setVisible(false);
                            this.jTextFieldUpdateMoney.setVisible(false);
                            this.jLabelAddMoney.setVisible(false);
                        }
                    }
                    showCustomerDebt(cust_id);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Amount must be numeric!");

                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter amount first!");

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select money Deposite or Withdraw option first !");

        }
    }//GEN-LAST:event_jButtonUpdateMoneyActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        // TODO add your handling code here:
        this.jButtonUpdate.setVisible(false);
        this.jTextFieldUpdateMoney.setVisible(true);
        this.jLabelAddMoney.setVisible(true);
        this.jRadioButtonDeposite.setVisible(true);
        this.jRadioWithDraw.setVisible(true);
        this.jButtonUpdateMoney.setVisible(true);


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldUpdateMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUpdateMoneyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateMoneyMouseClicked

    private void jTextFieldUpdateMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateMoneyActionPerformed

    private void jTextFieldUpdateMoneyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUpdateMoneyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateMoneyKeyPressed

    private void jTextFieldUpdateMoneyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUpdateMoneyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateMoneyKeyReleased

    private void jTableCustomerSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCustomerSaleMouseClicked

    private void jTableCustomerSaleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerSaleMouseReleased
        // TODO add your handling code here:
        String date = sale_list.get(this.jTableCustomerSale.getSelectedRow()).getSale_date();
        int sale_id = sale_list.get(this.jTableCustomerSale.getSelectedRow()).getSale_id();
        //  System.out.println(""+date);
        //   JOptionPane.showMessageDialog(rootPane,customer_id );
        showInCustomerSalesDetailTable(customer_id, date, sale_id);

    }//GEN-LAST:event_jTableCustomerSaleMouseReleased

    private void jTableCustomerProductSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerProductSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCustomerProductSaleMouseClicked

    private void jTableCustomerProductSaleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerProductSaleMouseReleased
        // TODO add your handling code here:

        int productSaleId = Integer.parseInt("" + this.jTableCustomerProductSale.getValueAt(this.jTableCustomerProductSale.getSelectedRow(), 0));
        //  System.out.println(""+date);
        //   JOptionPane.showMessageDialog(rootPane,customer_id );
        showInCustomerProductSalesDetailTable(productSaleId);


    }//GEN-LAST:event_jTableCustomerProductSaleMouseReleased

    private void jTableCustomerProductSaleDetail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerProductSaleDetail1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCustomerProductSaleDetail1MouseClicked

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        MessageFormat header = new MessageFormat("THE BEAUTY BAR " + jLabelCustomerName.getText().toString() + " Services REPORT");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            this.jTableCustomerSale.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(CustomerDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack2ActionPerformed
        MessageFormat header = new MessageFormat("THE BEAUTY BAR " + jLabelCustomerName.getText().toString() + " Products REPORT");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            this.jTableCustomerSale.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(CustomerDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBack2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails().setVisible(true);
            }
        });
    }

    public void showInCustomerSalesDetailTable(int customer_id, String date, int saleId) {
        try {
            tableModelCustomerSaleDetail.setRowCount(0);
            int counter = 1;
            ServiceDao ser = new ServiceDaoImpl();
            sale_details_list = saleDeatail.getAllSaleDetailbyCustomerId(customer_id, date, saleId);
            for (SaleDetailBeans salesDetails : sale_details_list) {
                Vector V = new Vector();
                V.add(ser.getServiceById(salesDetails.getService_id()).getService_name());
                V.add(salesDetails.getPrice());

                tableModelCustomerSaleDetail.addRow(V);
            }
        } catch (Exception e) {
            System.out.println("No data");
        }
    }

    public void showInCustomerProductSalesDetailTable(int saleId) {
        try {
            tableModelProductCustomerSaleDetail.setRowCount(0);
            productSaleDetails = productSaleDeatailDao.getAllProductSaleDetailsBySaleId(saleId);
            for (ProductSaleDetailBean psdb : productSaleDetails) {
                Vector V = new Vector();
                V.add(psdb.getInventoryBean().getInventoryName());
                V.add(psdb.getTotalCost() / psdb.getQuantity());
                V.add(psdb.getQuantity());
                V.add(psdb.getTotalCost());

                tableModelProductCustomerSaleDetail.addRow(V);
            }
        } catch (Exception e) {
            System.out.println("No data");
        }
    }

    public void showInSaleTable(int customer_id) {
        tableModelCustomerSale.setRowCount(0);
        sale_list = sale.getAllSalesByCustomId(customer_id);
        for (SaleBeans salesDetails : sale_list) {
            Vector V = new Vector();
            V.add(salesDetails.getSale_id());
            V.add(salesDetails.getSale_date());
            V.add(salesDetails.getDiscount() + " " + salesDetails.getDiscount());

            V.add(salesDetails.getTotal_bill());
            V.add(salesDetails.getPaid());
            V.add(salesDetails.getTotal_bill() - salesDetails.getPaid());

            tableModelCustomerSale.addRow(V);
        }
    }

    public void showInProductSaleTable(int customer_id) {
        tableModelProductCustomerSale.setRowCount(0);
        productSalesList = productSaleDao.getAllSalesByCustomId(customer_id);
        for (ProductSaleBean psb : productSalesList) {
            Vector V = new Vector();
            V.add(psb.getProdSaleId());
            V.add(psb.getCreatedAt());
            V.add(psb.getDiscount() + " " + psb.getDiscount());
            V.add(psb.getTotalCost());
            V.add(psb.getPaid());
            V.add(psb.getTotalCost() - psb.getPaid());

            tableModelProductCustomerSale.addRow(V);
        }
    }

    public void showCustomerDebt(int customer_id) {
        this.jLabelCustomerDebt.setText("" + customerDao.getCustomerDebtByCustomerId(customer_id));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdateMoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAddMoney;
    private javax.swing.JLabel jLabelCustomerDebt;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDeposite;
    private javax.swing.JRadioButton jRadioWithDraw;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableCustomerProductSale;
    private javax.swing.JTable jTableCustomerProductSaleDetail1;
    private javax.swing.JTable jTableCustomerSale;
    private javax.swing.JTable jTableCustomerSaleDetail;
    private javax.swing.JTextField jTextFieldUpdateMoney;
    // End of variables declaration//GEN-END:variables
}
