/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautyparlour.frames;

import beautyparlour.dialog.AdminLoginDialog;
import beautyparlour.dialog.PrintersAvailable;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage2
     */
    public HomePage() {
        initComponents();
        

  
        
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        int xsize=(int)toolkit.getScreenSize().getWidth();
        int ysize=(int)toolkit.getScreenSize().getHeight();
        
        System.out.println("x:"+xsize+" ysize:"+ysize);
//        this.pack();
//                this.setSize(xsize,ysize);

//        new PrintersAvailable(this, true).setVisible(true);


        closePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogin6 = new javax.swing.JButton();
        jButtonProduct = new javax.swing.JButton();
        jButtonLogin9 = new javax.swing.JButton();
        jButtonLogin10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRetail = new javax.swing.JButton();
        jButtonLogin12 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 11, 6));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 34, 19), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/beautybarlogo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 400, 420));

        jButtonLogin6.setBackground(new java.awt.Color(60, 34, 19));
        jButtonLogin6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/sale.png"))); // NOI18N
        jButtonLogin6.setText("Sale");
        jButtonLogin6.setFocusPainted(false);
        jButtonLogin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 400, 200));

        jButtonProduct.setBackground(new java.awt.Color(60, 34, 19));
        jButtonProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/services.png"))); // NOI18N
        jButtonProduct.setText("Services");
        jButtonProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 540, 400, 200));

        jButtonLogin9.setBackground(new java.awt.Color(60, 34, 19));
        jButtonLogin9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/customer.png"))); // NOI18N
        jButtonLogin9.setText("Customer");
        jButtonLogin9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 760, 400, 200));

        jButtonLogin10.setBackground(new java.awt.Color(60, 34, 19));
        jButtonLogin10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin10.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin10.setText("Customer Records");
        jButtonLogin10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 760, 400, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Software Designed By: Zaptox");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1010, 280, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("contactus@zaptox.com");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1030, 230, 20));

        jLabel1.setBackground(new java.awt.Color(60, 34, 19));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THE BEAUTY BAR ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 34, 19), 2, true));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 1920, 50));

        jButtonRetail.setBackground(new java.awt.Color(60, 34, 19));
        jButtonRetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRetail.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/retailicon.png"))); // NOI18N
        jButtonRetail.setText("Retail");
        jButtonRetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetailActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 400, 200));

        jButtonLogin12.setBackground(new java.awt.Color(60, 34, 19));
        jButtonLogin12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/customer_records.png"))); // NOI18N
        jButtonLogin12.setText("Daily Expenses");
        jButtonLogin12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 760, 400, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/login.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 60, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1920, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogin10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin10ActionPerformed
        // TODO add your handling code here:
        //        new SalePage().setVisible(true);
        //        this.dispose();
        new ShowCustomerPage().setVisible(true);
        //        genReport();
    }//GEN-LAST:event_jButtonLogin10ActionPerformed

    private void jButtonLogin9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin9ActionPerformed
        // TODO add your handling code here:

        new CustomerForm().setVisible(true);
        //        this.dispose();

    }//GEN-LAST:event_jButtonLogin9ActionPerformed

    private void jButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductActionPerformed
        // TODO add your handling code here:
        //        new CompanyProduct().setVisible(true);
        //        this.dispose();
        new ServiceForm().setVisible(true);
    }//GEN-LAST:event_jButtonProductActionPerformed

    private void jButtonLogin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin6ActionPerformed
        // TODO add your handling code here:
        //        new CustomerRecords().setVisible(true);
        new SalePage().setVisible(true);
    }//GEN-LAST:event_jButtonLogin6ActionPerformed

    private void jButtonRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetailActionPerformed
        new RetailPage().setVisible(true);    }//GEN-LAST:event_jButtonRetailActionPerformed

    private void jButtonLogin12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin12ActionPerformed
        // TODO add your handling code here:
        new DailyExpensesPage().setVisible(true);
    }//GEN-LAST:event_jButtonLogin12ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
                new AdminLoginDialog(this,true).setVisible(true);

    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    System.exit(0);
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }

    public void closePage() {

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin10;
    private javax.swing.JButton jButtonLogin12;
    private javax.swing.JButton jButtonLogin6;
    private javax.swing.JButton jButtonLogin9;
    private javax.swing.JButton jButtonProduct;
    private javax.swing.JButton jButtonRetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
