/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautyparlour.frames;

import beautyparlour.bean.CustomerBean;
import beautyparlour.bean.DailyInventoryReport;
import beautyparlour.bean.DailyReportBean;
import beautyparlour.bean.ProductSaleDetailBean;
import beautyparlour.dao.InventoryReportsDao;
import beautyparlour.dao.ProductSaleDetailDao;
import beautyparlour.dao.ReportDao;
import beautyparlour.daoImpl.CustomerDaoImpl;
import beautyparlour.daoImpl.InventoryReportDaoImpl;
import beautyparlour.daoImpl.ProductSaleDetailDaoImpl;
import beautyparlour.daoImpl.ReportDaoImpl;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import org.eclipse.birt.core.framework.Platform;
import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.HTMLRenderOption;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportEngineFactory;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.engine.api.IRunAndRenderTask;

/**
 *
 * @author Dell
 */
public class OverAllInventoryReportPage extends javax.swing.JFrame {

    /**
     * Creates new form DailyReportPage
     */
    DefaultTableModel tableModelReport, tableModelDetail;
    InventoryReportsDao inventoryReportsDao;
    private List<DailyInventoryReport> dailyInventoryReports;
    private List<ProductSaleDetailBean> productSaleDetails;
    private String date_for_report;
    String date2;
    ProductSaleDetailDao productSaleDetailDao;
    TableRowSorter<DefaultTableModel> rowSorter = null;

    public OverAllInventoryReportPage() {
        initComponents();
        this.getContentPane().setBackground(Color.white);

        inventoryReportsDao = new InventoryReportDaoImpl();
        tableModelReport = (DefaultTableModel) this.jTableReport.getModel();
        tableModelDetail = (DefaultTableModel) this.jTableDetails.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelReport);
        dailyInventoryReports = new ArrayList<>();
        this.jTableReport.setRowSorter(rowSorter);
        LocalDate date = LocalDate.now();
        productSaleDetailDao = new ProductSaleDetailDaoImpl();
        productSaleDetails = new ArrayList<>();
        this.date2=""+date;
        showInTable(date + "");

    }

    public void showInTable(String date) {
        tableModelReport.setRowCount(0);

        int serial = 0;
        dailyInventoryReports = inventoryReportsDao.getSoldQtyOFInventories();

        for (DailyInventoryReport dir : dailyInventoryReports) {
            Vector V = new Vector();
            serial++;
            V.add(serial);
            V.add(dir.getInventoryBean().getInventoryId());
            V.add(dir.getInventoryBean().getInventoryName());
            V.add(dir.getSum());
            V.add(dir.getCreatedAt());
//
//            total_profit += dailyReportBean.getTotal_bill();
//            total_customers += 1;
            tableModelReport.addRow(V);
        }

    }

    public void showInTableInventoryDetails(Integer id, String date) {
        tableModelDetail.setRowCount(0);
        int serial = 0;
        productSaleDetails = productSaleDetailDao.getAllProductSaleDetailsByInventoryId(id, date);

        for (ProductSaleDetailBean psdb : productSaleDetails) {
            Vector V = new Vector();
            serial++;
            V.add(serial);
            V.add(psdb.getInventoryBean().getInventoryName());
            V.add(psdb.getCustomerBean().getCustomer_name());
            V.add(psdb.getQuantity());
            V.add(psdb.getCost());

//
//            total_profit += dailyReportBean.getTotal_bill();
//            total_customers += 1;
            tableModelDetail.addRow(V);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetails = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSerach3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(60, 34, 19));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, 30));

        jPanel1.setBackground(new java.awt.Color(20, 11, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(60, 34, 19));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THE BEAUTY BAR");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1320, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Overall InventoryReport");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButtonBack1.setBackground(new java.awt.Color(60, 34, 19));
        jButtonBack1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/print_1.png"))); // NOI18N
        jButtonBack1.setText("Print Report");
        jButtonBack1.setFocusPainted(false);
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 220, 40));

        jTableDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S#", "Item", "Sold To", "QTY", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDetails);
        if (jTableDetails.getColumnModel().getColumnCount() > 0) {
            jTableDetails.getColumnModel().getColumn(0).setMinWidth(40);
            jTableDetails.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableDetails.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableDetails.getColumnModel().getColumn(3).setMinWidth(110);
            jTableDetails.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTableDetails.getColumnModel().getColumn(3).setMaxWidth(110);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 660, 460));

        jTableReport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S#", "Id", "Item", "Total Qty Sold", "Sold Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableReportMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableReport);
        if (jTableReport.getColumnModel().getColumnCount() > 0) {
            jTableReport.getColumnModel().getColumn(0).setMinWidth(40);
            jTableReport.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableReport.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableReport.getColumnModel().getColumn(1).setMinWidth(60);
            jTableReport.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableReport.getColumnModel().getColumn(1).setMaxWidth(60);
            jTableReport.getColumnModel().getColumn(3).setMinWidth(110);
            jTableReport.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTableReport.getColumnModel().getColumn(3).setMaxWidth(110);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 630, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beautyparlour/util/report.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 70, 30));

        jTextFieldSerach3.setBackground(new java.awt.Color(20, 11, 6));
        jTextFieldSerach3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSerach3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSerach3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jTextFieldSerach3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldSerach3.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldSerach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerach3ActionPerformed(evt);
            }
        });
        jTextFieldSerach3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSerach3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSerach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ReportPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        MessageFormat header = new MessageFormat("THE BEAUTY BAR Overall Sale Inventory Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            this.jTableDetails.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(InventoryPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jTableReportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReportMouseReleased
        Integer id = Integer.parseInt("" + this.jTableReport.getValueAt(this.jTableReport.getSelectedRow(), 1));
        String date = "" + this.jTableReport.getValueAt(this.jTableReport.getSelectedRow(), 4);
        showInTableInventoryDetails(id, date);
    }//GEN-LAST:event_jTableReportMouseReleased

    private void jTextFieldSerach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerach3ActionPerformed

    private void jTextFieldSerach3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerach3KeyReleased
        // TODO add your handling code here:

        tableModelDetail.setRowCount(0);
        this.jTableReport.getSelectionModel().clearSelection();
        this.jTableDetails.getSelectionModel().clearSelection();

        try {

            String searchData = this.jTextFieldSerach3.getText();
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchData));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldSerach3KeyReleased

    /**
     * s
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverAllInventoryReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverAllInventoryReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverAllInventoryReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverAllInventoryReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverAllInventoryReportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDetails;
    private javax.swing.JTable jTableReport;
    private javax.swing.JTextField jTextFieldSerach3;
    // End of variables declaration//GEN-END:variables
}
